name: Cypress Tests and Perf comparison
on: [push]

jobs:
  cypress-run-main:
    name: Run Cypress tests on main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:storybook
          wait-on: 'http://localhost:6006'
          wait-on-timeout: 120
          browser: chrome
          config: integrationFolder=cypress/integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: perf-benchmarks-main
          path: cypress/downloads

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:storybook
          wait-on: 'http://localhost:6006'
          wait-on-timeout: 120
          browser: chrome
          config: integrationFolder=cypress/integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: perf-benchmarks-branch
          path: cypress/downloads

      - name: Download main artifacts
        uses: actions/download-artifact@v2
        with:
          name: perf-benchmarks-main
          path: perf-benchmarks-main

      - name: Download main artifacts
        uses: actions/download-artifact@v2
        with:
          name: perf-benchmarks-branch
          path: perf-benchmarks-branch

      - run: ls -R

      - name: Run perf-addon-cli
        id: run-cli
        run: npm run sb-perf -- -c /home/runner/work/react-1/react-1/perf-benchmarks-main -b /home/runner/work/react-1/react-1/perf-benchmarks-branch

      - name: Upload sb-perf
        id: sb-perf-upload
        uses: actions/upload-artifact@v2
        with:
          name: sb-perf
          path: sb-perf
